#!/bin/sh
# Set CANDLEHOME before starting or alter the next line to set installation directory for TEPS
if [ "$CANDLEHOME" = "" ]; then export CANDLEHOME=/opt/IBM/ITM; fi
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT NODE,NODETYPE,NODELIST,LSTDATE FROM O4SRV.TNODELST"' >QA1CNODL.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT NODE,O4ONLINE,PRODUCT,VERSION,HOSTADDR,RESERVED,THRUNODE,HOSTINFO,AFFINITIES FROM O4SRV.TNODESAV"' >QA1DNSAV.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT SITNAME,AUTOSTART,LSTDATE,REEV_DAYS,REEV_TIME,SITINFO,PDT FROM O4SRV.TSITDESC"' >QA1CSITF.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT ID,LSTDATE,FULLNAME FROM O4SRV.TNAME"' >QA1DNAME.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT OBJCLASS,OBJNAME,NODEL,LSTDATE FROM O4SRV.TOBJACCL"' >QA1DOBJA.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT GRPCLASS,ID,LSTDATE,GRPNAME FROM O4SRV.TGROUP"' >QA1DGRPA.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT GRPCLASS,ID,LSTDATE,OBJCLASS,OBJNAME FROM O4SRV.TGROUPI"' >QA1DGRPI.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT ID,LSTDATE,LSTUSRPRF FROM O4SRV.EVNTSERVER"' >QA1DEVSR.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT KEY,LSTDATE,NAME FROM O4SRV.CCT"' >QA1DCCT.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT ID,LSTDATE,MAP FROM O4SRV.EVNTMAP"' >QA1DEVMP.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT PCYNAME,LSTDATE,AUTOSTART FROM O4SRV.TPCYDESC"' >QA1DPCYF.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT ACTNAME,PCYNAME,LSTDATE,TYPESTR,ACTINFO FROM O4SRV.TACTYPCY"' >QA1DACTP.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT ID,LSTDATE,NAME FROM O4SRV.TCALENDAR"' >QA1DCALE.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT ID,LSTDATE,SITNAME FROM O4SRV.TOVERRIDE"' >QA1DOVRD.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT ID,LSTDATE,ITEMID,CALID FROM O4SRV.TOVERITEM"' >QA1DOVRI.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT GBLTMSTMP,OBJNAME,OPERATION,TABLENAME FROM O4SRV.TEIBLOGT"' >QA1CEIBL.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT GBLTMSTMP,DELTASTAT,SITNAME,NODE,ORIGINNODE,ATOMIZE FROM O4SRV.TSITSTSH"' >QA1CSTSH.DB.LST
${CANDLEHOME}/bin/itmcmd execute cq 'KfwSQLClient /e "SELECT NAME,RESERVED FROM O4SRV.TCHECKPT"' >QA1CCKPT.DB.LST
